# TSMOM Strategy Configuration for Tinkoff API

# Strategy Parameters
strategy:
  lookback_period: 12  # months
  holding_period: 1    # months
  target_volatility: 0.40  # 40% annual volatility
  transaction_cost: 0.001  # 0.1% per trade

# Data Parameters
data:
  source: "Tinkoff"  # Data source: "Yahoo" or "Tinkoff"
  start_date: "2020-01-01"  # Tinkoff data available from ~2010
  end_date: "2023-12-31"
  frequency: "D"  # Daily data
  min_assets: 5

# Asset Universe - Russian Futures
assets:
  russian_futures:
    - "Si"      # USD/RUB Futures
    - "BR"      # Brent Oil Futures
    - "RI"      # RTS Index Futures
    - "MX"      # Moscow Exchange Index Futures
    - "GD"      # Gold Futures
    - "SBRF"    # Sberbank Futures
    - "GAZR"    # Gazprom Futures
    - "LKOH"    # Lukoil Futures
    - "NVTK"    # Novatek Futures
    - "ROSN"    # Rosneft Futures

# Backtest Parameters
backtest:
  initial_capital: 1000000  # ₽1M starting capital
  rebalance_frequency: "M"  # Monthly rebalancing
  benchmark: "RI"           # RTS Index as benchmark

# Risk Management
risk:
  volatility_lookback: 3    # months for volatility calculation
  max_position_size: 0.1    # maximum 10% in single asset
  stop_loss: 0.05           # 5% stop loss

# Output Settings
output:
  report_format: "markdown"
  plot_format: "png"
  save_results: true 