# TSMOM Strategy Configuration

# Strategy Parameters
strategy:
  lookback_period: 12  # months
  holding_period: 1    # months
  target_volatility: 0.40  # 40% annual volatility
  transaction_cost: 0.001  # 0.1% per trade

# Data Parameters
data:
  source: "Yahoo"  # Data source: "Yahoo" or "T-Invest"
  start_date: "2000-01-01"
  end_date: "2023-12-31"
  frequency: "D"  # Daily data
  min_assets: 20

# Asset Universe
assets:
  equity_indices:
    - "^GSPC"  # S&P 500
    - "^DJI"   # Dow Jones
    - "^IXIC"  # NASDAQ
    - "^FTSE"  # FTSE 100
    - "^N225"  # Nikkei 225
    - "^GDAXI" # DAX
    - "^FCHI"  # CAC 40
  
  bonds:
    - "^TNX"   # 10Y Treasury
    - "^TYX"   # 30Y Treasury
    - "TLT"    # 20+ Year Treasury Bond ETF
    - "IEF"    # 7-10 Year Treasury Bond ETF
  
  currencies:
    - "EURUSD=X"  # EUR/USD
    - "GBPUSD=X"  # GBP/USD
    - "JPYUSD=X"  # JPY/USD
    - "CHFUSD=X"  # CHF/USD
    - "CADUSD=X"  # CAD/USD
  
  commodities:
    - "GC=F"   # Gold Futures
    - "CL=F"   # Crude Oil Futures
    - "ZC=F"   # Corn Futures
    - "ZS=F"   # Soybean Futures
    - "KC=F"   # Coffee Futures
    - "CT=F"   # Cotton Futures

# Backtest Parameters
backtest:
  initial_capital: 1000000  # $1M starting capital
  rebalance_frequency: "M"  # Monthly rebalancing
  benchmark: "^GSPC"        # S&P 500 as benchmark

# Risk Management
risk:
  volatility_lookback: 3    # months for volatility calculation
  max_position_size: 0.1    # maximum 10% in single asset
  stop_loss: 0.05           # 5% stop loss

# Output Settings
output:
  report_format: "markdown"
  plot_format: "png"
  save_results: true 